apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgres-secret
  namespace: mlops
type: Opaque
stringData:
  connection: postgresql://postgres:REPLACE_WITH_POSTGRES_PASSWORD@postgres-postgresql.mlops.svc.cluster.local:5432/airflow
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-redis-secret
  namespace: mlops
type: Opaque
stringData:
  connection: redis://:REPLACE_WITH_REDIS_PASSWORD@redis-master.mlops.svc.cluster.local:6379/0
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret
  namespace: mlops
type: Opaque
stringData:
  webserver-secret-key: REPLACE_WITH_RANDOM_32_CHAR_STRING
