apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  admin.password: REPLACE_WITH_BCRYPT_HASH_OF_ADMIN_PASSWORD
  admin.passwordMtime: REPLACE_WITH_ISO8601_TIMESTAMP
  accounts.readonly.password: REPLACE_WITH_BCRYPT_HASH_OF_READONLY_PASSWORD
  accounts.readonly.passwordMtime: REPLACE_WITH_ISO8601_TIMESTAMP
