fullnameOverride: sealed-secrets-controller

image:
  registry: git.alexshishin.ru
  repository: mlops/sealed-secrets
  tag: "latest"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
