apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console
  namespace: mlops
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio-console.alexshishin.ru`)
      kind: Rule
      services:
        - name: minio-console
          port: 9001
  tls:
    secretName: minio-console-tls-secret
