architecture: standalone

auth:
  enabled: true
  existingSecret: redis-secret
  existingSecretPasswordKey: redis-password

image:
  registry: git.alexshishin.ru
  repository: mlops/redis
  tag: "latest"

commonConfiguration: |-
  appendonly yes
  save ""

master:
  persistence:
    enabled: true
    size: 2Gi
    storageClass: local-path
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
