image:
  tag: "v3.15.0"

backendStore:
  postgres:
    enabled: true
    host: postgres-postgresql.mlops.svc.cluster.local
    port: 5432
    database: mlflow
  existingDatabaseSecret:
    name: postgres-secret
    usernameKey: postgres-user
    passwordKey: postgres-password

artifactRoot:
  s3:
    enabled: true
    bucket: mlflow-artifacts
    existingSecret:
      name: minio-secret
      keyOfAccessKeyId: root-user
      keyOfSecretAccessKey: root-password

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: http://minio.mlops.svc.cluster.local:9000

auth:
  enabled: true
  existingAdminSecret:
    name: mlflow-basic-auth-secret

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

service:
  type: ClusterIP
  port: 5000
