apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: helm-cert-manager
            chart: cert-manager
            chartRepoURL: CHART_REPO_URL_PLACEHOLDER   # TODO
            chartVersion: CHART_VERSION_PLACEHOLDER     # TODO
            namespace: cert-manager
            wave: "-1"
          - name: helm-postgres
            chart: postgres
            chartRepoURL: CHART_REPO_URL_PLACEHOLDER
            chartVersion: CHART_VERSION_PLACEHOLDER
            namespace: mlops
            wave: "0"
          - name: helm-redis
            chart: redis
            chartRepoURL: CHART_REPO_URL_PLACEHOLDER
            chartVersion: CHART_VERSION_PLACEHOLDER
            namespace: mlops
            wave: "0"
          - name: helm-minio
            chart: minio
            chartRepoURL: CHART_REPO_URL_PLACEHOLDER
            chartVersion: CHART_VERSION_PLACEHOLDER
            namespace: mlops
            wave: "0"
          - name: helm-gitea
            chart: gitea
            chartRepoURL: CHART_REPO_URL_PLACEHOLDER
            chartVersion: CHART_VERSION_PLACEHOLDER
            namespace: mlops
            wave: "1"
          - name: helm-gitea-act-runner
            chart: gitea-act-runner
            chartRepoURL: CHART_REPO_URL_PLACEHOLDER
            chartVersion: CHART_VERSION_PLACEHOLDER
            namespace: mlops
            wave: "1"
          - name: helm-mlflow
            chart: mlflow
            chartRepoURL: CHART_REPO_URL_PLACEHOLDER
            chartVersion: CHART_VERSION_PLACEHOLDER
            namespace: mlops
            wave: "1"
          - name: helm-airflow
            chart: airflow
            chartRepoURL: CHART_REPO_URL_PLACEHOLDER
            chartVersion: CHART_VERSION_PLACEHOLDER
            namespace: mlops
            wave: "1"
  template:
    metadata:
      name: '{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
      labels:
        app.kubernetes.io/part-of: bootstrap
    spec:
      project: default
      sources:
        - repoURL: '{{.chartRepoURL}}'
          chart: '{{.chart}}'
          targetRevision: '{{.chartVersion}}'
          helm:
            valueFiles:
              - $values/apps/helm/{{.chart}}/values.yaml
        - repoURL: GIT_REPO_URL_PLACEHOLDER   # TODO: URL этого репозитория
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
