apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: namespaces
            path: namespaces/dev
            namespace: argocd
            wave: "-2"
          - name: ingress-main-tls
            path: ingress/main-tls/dev
            namespace: cert-manager
            wave: "-1"
          - name: platform-frontend
            path: apps/platform/frontend/dev
            namespace: mlops
            wave: "1"
          - name: platform-serving
            path: apps/platform/serving/dev
            namespace: mlops
            wave: "1"
          - name: ingress-airflow
            path: ingress/main/airflow
            namespace: mlops
            wave: "2"
          - name: ingress-frontend
            path: ingress/main/frontend
            namespace: mlops
            wave: "2"
          - name: ingress-gitea
            path: ingress/main/gitea
            namespace: mlops
            wave: "2"
          - name: ingress-minio
            path: ingress/main/minio
            namespace: mlops
            wave: "2"
          - name: ingress-minio-console
            path: ingress/main/minio-console
            namespace: mlops
            wave: "2"
          - name: ingress-mlflow
            path: ingress/main/mlflow
            namespace: mlops
            wave: "2"
          - name: ingress-serving
            path: ingress/main/serving
            namespace: mlops
            wave: "2"
  template:
    metadata:
      name: '{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
      labels:
        app.kubernetes.io/part-of: bootstrap
    spec:
      project: default
      source:
        repoURL: GIT_REPO_URL_PLACEHOLDER   # TODO: URL этого репозитория
        targetRevision: main
        path: '{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
