apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: mlops
labels:
  - pairs:
      app: serving
      env: dev
images:
  - name: git.alexshishin.ru/mlops/serving
    newTag: e84e79af12fc683a22364cd214d67b628271b684
