apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: mlops
labels:
  - pairs:
      app: serving
      env: dev
images:
  - name: git.alexshishin.ru/mlops/serving
    newTag: 861cd7aeb1d85174f2c2b52ef4ebe5b9809a1b0b
