apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: mlops
labels:
  - pairs:
      app: serving
      env: dev
images:
  - name: git.alexshishin.ru/mlops/serving
    newTag: 6a69d3c2af4b35335be78882d61e518ab7d717d7
