enabled: true

giteaRootURL: "https://git.alexshishin.ru"

existingSecret: gitea-act-runner-secret
existingSecretKey: token

preExtraInitContainers:
  - name: install-kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["/busybox/cp", "/kaniko/executor", "/kaniko-bin/executor"]
    volumeMounts:
      - name: kaniko-bin
        mountPath: /kaniko-bin
  - name: install-kubectl
    image: curlimages/curl:8.10.1
    command:
      - sh
      - -c
      - |
        curl -fsSL -o /kaniko-bin/kubectl https://dl.k8s.io/release/v1.37.0/bin/linux/amd64/kubectl
        chmod +x /kaniko-bin/kubectl
    volumeMounts:
      - name: kaniko-bin
        mountPath: /kaniko-bin

statefulset:
  serviceAccountName: gitea-act-runner-podmgr
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraVolumes:
    - name: kaniko-bin
      emptyDir: {}
    - name: kaniko-docker-config
      secret:
        secretName: kaniko-registry-creds
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: ci-workspace
      hostPath:
        path: /opt/ci-workspace
        type: DirectoryOrCreate
  runner:
    config: |
      log:
        level: info
      runner:
        labels:
          - "shell:host"
      cache:
        enabled: false
      container:
        require_docker: false
    extraVolumeMounts:
      - name: kaniko-bin
        mountPath: /kaniko-bin
      - name: kaniko-docker-config
        mountPath: /kaniko-docker-config
        readOnly: true
      - name: ci-workspace
        mountPath: /ci-workspace
    extraEnvs:
      - name: DOCKER_CONFIG
        value: /kaniko-docker-config
  dind:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
