apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-postgres-secret
  namespace: mlops
spec:
  encryptedData:
    connection: REGENERATE_WITH_KUBESEAL
  template:
    metadata:
      name: airflow-postgres-secret
      namespace: mlops
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-redis-secret
  namespace: mlops
spec:
  encryptedData:
    connection: REGENERATE_WITH_KUBESEAL
  template:
    metadata:
      name: airflow-redis-secret
      namespace: mlops
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-webserver-secret
  namespace: mlops
spec:
  encryptedData:
    webserver-secret-key: REGENERATE_WITH_KUBESEAL
  template:
    metadata:
      name: airflow-webserver-secret
      namespace: mlops
    type: Opaque
