---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-postgres-secret
  namespace: mlops
spec:
  encryptedData:
    connection: AgBceJQgzEpp1u8I1wzF3tjUoMgvhHe7ncQhvf+SJgK3UV/0i9fqEu9tB1JlfoRFkGFmuSSOp3Pfd0OgiNaugWJdtH8s9EgVtPWuCd8/eQuXSGFY8GvG7bVZYelknqgwkqQeMkFYLaSMgkvZua5p0RdAvhUq+tfJeHjHsC+PloRfanRwAJcnXOZIwY1wQT734GkHLU6d75oyMGeCwyq0CtX+vT+AuWA/LSY3Pk5GD2WU1thwjOPS6PRNohLixUARXjb2LtpzOl3rPujqZFRHTktMB17KKsJCtbL9YlGSPofy3p/6BtGDPWV2e+HJkOWJIejtq/XYxE1pZgGPOUuexfLMC9s0lc5MyIyKKyPM6Yq6USxCG2KC2jPnOSu6UgOLQpywZeEzmdobQwW5FbK37Y4alTNaUkryqf2uqgSgPHtrzlE1hY1Kbw7uc8gMNuFzQKN+saLzNyaC09RvIKPw8jKUqkcfdmoYCFzBaiSadpicUdVbdlYuebOokPW4rOzm65POH9BHMp0z1FGyqZr1YSpRN2NOC8gyOPOZThLZyyKHSTd/o0V+9RwAEv1YsLtl/ZPxgDYgvkH0V5pnB7GuDPWWNGTvaCjmtUA4iKwlPT0Qs/Ej60erdgoFxeQt8+sJuVU47ftUkz1siu/tP05F4pktlb6nG0Wij5jkB9DvMa7XW39I9DAXs2nHpXISaYi6zYaNEbi22Ea0CviUU0wH3IkfveQKahnEuN+xxmnaGL9hSVC47SWrEZdyZNFJtb77AidWaDXe7G/D9C5EugTjYnI5XyP9ilj+gP9Lyd5mkkjxqPHbJpt1zNKNBbPRhnwHEnAFJu5Q/yehyrPVwoLGtqDJl8arbK9m9A==
  template:
    metadata:
      name: airflow-postgres-secret
      namespace: mlops
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-redis-secret
  namespace: mlops
spec:
  encryptedData:
    connection: AgBg9Q3qEoddxZCJuDNI4rbBAVepJQH0UbNwCMWIirJnuU6i1DP4oYvDbMVq0uOFWDGRsI5Ez9duIJGR4BQxvPjmDMht7hrBanCKtR2WTxcKN5qNDzqxk4xTVnK1pMsWPDTreTseGgPW4i1jjEM/un/o9Rw/8fthZFRMmJORIjq4S67kmxsQbWpYJILg+kmrhytfAPls6/w6qDWUUx4wW6snoLxHK38zW9A78nDZuSFTs896QT7e8egE2DKcFEVy3cF5WR87hncWr6/5GoMBTt30vkF8Tuwru5lkFAyZeAlvjF5uopqNMfsFtvWZz5DbVgnX9tEZdh9Cmn4TLe/uTOW6Yx+O4D+lRPfUwq/CyXXB0tpNcz5DUyihp8RSptRzY1IcvlyJw7+/7dI2JvVG7IS0g5Vy/EJvb3itTKdLgkXdrUcnStXtTdORzpf1/qhACJvqot7nZ7B/5BnVA3Boc/7K4EVO0aKmZoCnqeFKV9YutZ2KdAV2VIgmZ6+pcNT6fVy1wFcoqSKlTtNkMourNhhkAa5/DHMuVmKDrYELKIPcbIjAQhz6qtufxKLo+wmA7WXpCoIyshhlJ6JjiqLk6EKvvKPF31efHCUBAtau8ObXudSqe37QAT8d9S3ENnlyOC83wjejTNncbZD8WzwO5gnEqS39qNj2lClHnR+O00PfvSzuYtHG90PfVh19TYlKd/FHvx3Pr/Eu9pONTTEtFQpVt5Em7uFFFdrWT0pXo6TxC8KRcV4UC5dFNeUBjoZXFSvEunnKx9v13O1X6dSxZ/MICTMA+2vaBT/OO7fVJKjxul/hRq6dwuG0OPxwYxc=
  template:
    metadata:
      name: airflow-redis-secret
      namespace: mlops
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-webserver-secret
  namespace: mlops
spec:
  encryptedData:
    webserver-secret-key: AgApE6jp+FIBPSGxsXq/f0JKLkM2aWERNi3oEtebXEIHuWJLAdyY3fvVD7Osco4ZiS58z+axvjNk4jOQECO1P6wTC26O1Y152sGoYSuyHyOQGBS1LxERZ1grNEfQqAyr1sTA+vNtOxop+gUL5ZWGida/cQmp49xST+4rmAUeSca9OhKTg/c5BLztga10+pR3XxRbkO9PAN5pr9RQFMxJMZyEsqYUsUZT3ylfU9BIz0BMkw7dqKqOKSHy1wm1eNY5Lnuy8H21Uczjk8nDFMv8mgFPSb1bLf+NWzmyw78+0P0oNIN3b4hXD6o0TAByxFkbguKioqmgecYVe/K+56ztNgdutfJj+X6kKLF6ZhCuqeuxNCOcwiRhwD6KgcJJ+9CaBh1o06UBbzEWQ6FXciyCvEVDdUlzJzkYzlEn3LhSvLevSZT9uXtMS8KzWOmTV3dOkuHEaVco5+Ongl1VUukUQu5aI/u2H+3ZmxLJI5vOrcPOoGeKEfFJ7Hc3GVhUVu6Wtg6nb2flLAEQajGcAh2gblCVx2qryrfHMhWRI7x7LSlyj7PazTNHwC1uTE5Az6Igf2EzwMV8aQ/LHex1W+84fQvyVq5dWlTaWXWyuPj7pnCcwNIvubBkI6pElJ3Lw/sTWeKcJctHYvb7oPgc1kcYQJN8TyI5O4sjxYaSGvEvP7U2AhYflsGTc5zdS8uk4BvKF0XWYAglSjrn+xGCg+tNGEQk0LUj1Wutv9wIa6kc0iFdFv8bKTymFhS3VMCnx3suSy+nBwTiXoAKsTyAANlhnhp4
  template:
    metadata:
      name: airflow-webserver-secret
      namespace: mlops
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-fernet-key
  namespace: mlops
spec:
  encryptedData:
    fernet-key: AgB1muWdqbJIUmFdX5eFiLFzaADEMsjfaeDM0hyDp3F37O43qzvP7VLY/Sx5avXi+daLnlG5K9y0uHwsfYh35DRYCiaPU/qNEbCArSLvC8WDjrG5o3lVQFZyu1oEI9LUDYNkIn/C7LKwFWX67or7VSU7uPtPiwWodzrxu1cr4XEqe+JSQ6cazmctrw06dv5LAZxKDdaWPtdtsth3AjiRokWnEXmDTylWlBzT/0Ek9fnTVSNtIq7RrQCh5TpXnLAoZzeh6Pxs7Clxi4BUmIvL6SC+i2r/+aTrPE4Tj0LA3M7IZog8gsUXblJK1Eil8P8Fjf2GDBxarKmUXDIjvRFAjGxbqpVdEzvY7nLFHqnBjCesVIhjxET97pJRtWUW1D5OoR/2jFfMCBxFOEQoW5i71eyXcjY0g/n+lR+TgfP1r4w5pnLcrKWtoIjmV8ENuO1t9H85NSHxjiYo85GVw802uQxq/TDGgoahAwTnfvwVTXYpOqZ4t3hxOmotQAO4rFx7ixc5yvb4rH7V/AwHXyBFKk4q6dvdUrQ3rzaesSItpLjowayZ+GM/auJiZTxvfx+S4EDTczzvsMvusOoaWtzBY+cs2bJ6cPzzUCDc+P17eZ3N7ii4QgYt/6mmeJsOFuzj5NRjbKiDFaWWT1+XKzO91flhpoWi0wF+2jP4WPzoqoFUDiLRvJX5iZ+Bv/yqpVL91TX+Tyc8rXPTGaM9EiYE5UrfGiGXle0UFCGK0RRJlYXCe0KhG5piok5apoR0vw==
  template:
    metadata:
      name: airflow-fernet-key
      namespace: mlops
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-api-secret-key
  namespace: mlops
spec:
  encryptedData:
    api-secret-key: AgBZp25DfVQWbfQ/8PnK1QIKpUIxTZHtNap99TrF7FroDvsb5XpGrISLY/UZn4r9Qo25I1EgMEFOaUIESuEdWpeUHo9L301tHGnlP0h5OptTOSNCaapTybBc/HqN0JuTv+2gBBAjsMi5Yh7+kPhVJQF0wyk323K6k0bl8GYRBBwR2T9M0ES1DcwNV14XroSsAcsR6LCfbz4E1rICtnfl8wxePYkGsZXDFnW58BOrJRF2D5vtd+DZlOjdnsvRW8zz7hkfMoXmXCHiq9LNBIzInu13fB/Ek+trf7hlmDERSKslDb7nuLmkgHU+QLtm5UChyVl99T7m+tYoZDiWChF6vhJlI7UNZ9647My0MHd7fyV6P150Yprj5GxXZHoRdqZFvuN6YEzMUoNQZlNXMOIdZ15AtZeDTEJxW7abzSz/ZUci75fUD+/WsLPZFM2H2evm2r8b3BmPa3/lUC5UAJO9hnAvweVfw3cb5jSwB+ZWO3OP8crgqfvFOhxGD+1qU5dis/MTS3bo4enj6H+7cJk2LZqayv1Ufhq8Er9HNJfAMGfjKn5jRsC4QZft7jO8bMEyHeC+A9ThgmWmTxH4K2u+71Umag0TCygkhyMSkd8oCFIRnslTu3Zel6yLjpm1O5mcWolGliTwaknqZNqY5gMkGduh+YBH5QiLGAiMG7jgqKfetqMCSbfxaxy4EuF2FVHPcqqhWN2Yw7etsnP8ztTC1O0D+bL15GB0Yh+dhzgOBMj528rUC+aenF2hXuOo8glH2h+edbt6KLinrTrA29RA3D5y
  template:
    metadata:
      name: airflow-api-secret-key
      namespace: mlops
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-jwt-secret
  namespace: mlops
spec:
  encryptedData:
    jwt-secret: AgAZ75R98xdQpm24ZVugPKnEm80+DLw1T88HyjSml+7Vy34k8ivInKifQ4Ev7z5Y4TEwZh2ViXSFyotE7O4Pzf3snVVLHZVfe1K8uOHNOnwdVD70VkQKkZbA8qwrsLSMKRc/ZDxpV/cspNnKaYfZz/9rIy3oKqHJ2aQH3DKhjSMNq3ATexVxFM9T0pUZLYzGff1CjkuPLAIPHqQjU4j30TH/+XjjYimoYdNfnE/HEJTuftILfMycwZoGo+8QsOtI8NSPK9uZhltxHrqbBNIKNpBusLZoy2syyz/oSoweK4aGJ+kxuDYEyc+nZN8EnGF8AlpuDypARvwHjQTwH3+BEI1XYp3Ny/7pH/21OfgEwbc96THa7aUK35+uOOTp4N83vR8HaEbnIXGUDQj3MyKA9agHFoK2iAzb5MM+n2uhJRozMbT2lz39eSslT0/WuVPpm4dCL7/jp1mYWLeO5B5sjKCP2KcS+N5k1KwCcmzMuSt+sRF6s2s8+8e2n1fzIEl6e+j4XQtUy2JpPOBKD7Gu3bqQlMon3L2+1Jyvsf8jVDyN3XwFkuIO6NxmP2EiClcGEI0K1FCrsvl+r9o44G7h87ZIiTFtzI65Yhqw+sX3zQyHpK2L5j9QFyqeTWgg8u4MLtL1DDw6Sbm5YBgvKmcLsFAMYTfI+pMUJo6qZR/JV15+vqCcQm4FtSQrL239078YF9ba2P/vVitNrHREa5gSYpJVnR+fll499DLnatnteBWrQ24PjNAFc9Kt/azRB8hH98KogoGj9ZoYK/yLNCOyBkKw
  template:
    metadata:
      name: airflow-jwt-secret
      namespace: mlops
    type: Opaque
