---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-admin-secret
  namespace: mlops
spec:
  encryptedData:
    password: AgCU53Qrinkwnls5XfXiITJhi2+RnCThVoSe95DF7QMW1/OvX9NA3Dx0ICQsogBra9VfAwOFRp+Mhf+vQhAdCefMmfvY23pU3CgysnsQb6qB38k1K7EWkaypue3KWDYTf9WtVJmHvB/hP4mYBQTOdk1lXQyN20+dGkPs2Qt0urv9TOKWr1AS/x+9hhu2X1siHFdoFsmkDBqsNaXHdrpnsa2ABmjDixwvUGdzqVrrtUVY0PTRrBFo7MZ9qQ3s11fL9qwgEOYt8ImlcSVJ85Q8wZeHPkV26otzVAVpw5rRLmNROqJnjKc+O7dox7rY/NpYUdGbjjU/yy0ahdUx58CgvR/Db2jwEAlnNOYW0ThI4CFQ2LYtWy453EqvpQUBug3Tg8JZ6aoMvdwqjRuyCLGbaClJbcNm3I5Y2EYJt+cj6WvxVpVXnRlEmu28FRp5Sepupmodq6fXFPeKmXqm0Cz4tFXgC5uwoRWvUlQh3p0ufCEr0KpGwD4KOwiJ0R0x6Ba6Ef6WmDsHGEeJLPpTCAq6lcOOV0u+zJ8BQ+SLxKzd9HnVCWZV8yag6IomC0iF2bpze1MAq7yqaPsEIqBBtg84RO7pJaJHGMQ0RlGKtoGOphZxSlzPXNmlyKZ4x9laCI4b94webqs0Z7mlgbW3SWejgBNlpcD62H6bIrlDsNIN3uNyA0TTOfmKDeBXEbxZ5zaykxruv0COfqqOX4Yk
    username: AgAIk1cdhzeCQsK4U9ZB4DWtfh7MLs3G2jkSJlnoczuqm9L4J9ORqxcQhOyKsagcAffBVVdJnMCwZpykzNhL0N0fBJ4Pt/E7sDZDro+9WGkgnr/Qhgt/udfZ8ShFZLAop0imQEoZ97VT+HZ5l38nRB1wwl1u2aLIVqFmxOAhQyx9/yhuoar7WSffUyNiyiaeHHU8kgA0jA4LRAc8qurynqvfQCSpdYvyfW1vtvoaA/L7MWyZMqO/bQ70V1BxeGmD+8lByHOtbSRJEL9a4sRLEdWACmgdC7PcBHz8Qas3YRCx1zq6+W9EYRRncs0r3JU90m+lEfi1a99NEq1Irv7FzopQHG9/2q/G9XHwStzLbforK5618JPfBqfVda2vI3abch/vZWIJraByv661IYGt/YADKgf4BelB3x+jE9WLSMOgaXso2mxYU5K8vyqUY5cpohBhj+HI5jg2rK7KWxNj3X+WfT5LArNCzOqFbArggz9PUUwO6se1KGAmQeE4GNGwPfHRNzLSebgEwxgotakLegvkxJSXfBkciWRlPG0QHI8/gi4Byb7Ls0YsUM+xyOlNwSlusGeC2rjRORexnTvHB4c9btlxYuwLjBmt6ycd0WivvAiGU9fTCJh6cJaFS48Vm5AoP8WiKPGKvCHdNqVvTiUr22f5GznKtTu1G1aEefJAOv9TKXuVJIOThW5HvggkWWBtwFJsTe/lQgGkrlcW
  template:
    metadata:
      name: airflow-admin-secret
      namespace: mlops
    type: Opaque
