---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-jury-secret
  namespace: mlops
spec:
  encryptedData:
    password: AgAgPvoBWyaI+CW58OfJSWY5zLqvQwaju5MKvNhtYNzBfd7KwgUkDBnYwYyMraCGj8T+CyBA8G+58GdnBaZc0Sf0vDSvSAXLhOAstrRfej5DQv2HVJm85l02r6XRkk1C1AIcr8gp/abrhJfLbapr/2HEsMD+xA7WPwKw4E/UEwyPUghL4Nr6WYl7zMTXWzEN7epul8tHRQRQFY+JSrSl9VR/V12UVKKW9UICFCmwVfP+6gg5A9nCydvwkeBtAfuLzFtufxawv8Tq1WeB5A27ueRFCJZfjryTrqYvTeyCD7QYQDov/CVkQ6t8h0/WN/zIhMnXdLd0/U2j5DZan/Y2sWaXr7syX1X93LCLmjNLUll3rIiQhUvMVK1bgHOz+E1/rZUuvwkh4r7bqIgyzAgpMujtSCA6Mdmf8y0AHaPUUK0lsu5Ki710qbQI95jjtyDPwIodmhYJgTeWvmt6mDAWcUKtRPZafUhr49SWujMNoZhw2L+urT6FGtq40MpQ26OztqK4P7nyj+/qSnPAvtk8knaSO6wF7G/ONzwaHs2VgY18bKlKqgEwXl/rz5zhqbsPEMKBohfRSnlIlT/cz6feak8L0dkgs05t+9GmTbZwc0/SIRCrdst0O6C/9MLs6Ciqb5IxYJwN/seGfI6MDawq4lwQQNmujnaw6w4NFPOxyNsd0a1l8r7uf9ZHTwT52pQgxEtstGbHDc2da3w=
    username: AgAl51fvVHZsdLQo+CXGe6RNrPM/GoCO1iQ2NF5xoa60UQF0K2s6qbHhDEwt8stiYDjq+3EQQB61EeVJaI16v+Cp2c094YMc6rfyUZEC9Qubk0ZGMSMRb9jpE2fs10pF4D3jX/W9gqa6EQpMCVR8931OR6cj08DH1c2ZJe3hNwigifc2Sg3AsTnqoUp8vHF9B8SXdIZB4tbcyj+5dU7WKX73OCoR1MRL8l2vifpVeR8PwU+6ubdrYKgKDu8Fzul1DaHDplh3VGBo4QGtgIDaioZhinFojXxzw4n99XxwW+oZpSElP9vu5obace0jpVwM55bERP5KKafUJZI99RMlWQAQtB19yMT5q3rA2/s+jGerPl/+JXu+hudHJ1wfDulS18zVCD08rrtfebJ69hMrLQ1NbAP964f0t+UNYeqOFsF2xKtksq9ySzqLcUM1kH+5AIYkUBTvDOqqjDAqc/qDPZxeJqyL7hbtKaLZ5/jrZyRDF4reKLGrWSKhk/C0HpKKVv2RQpRoHwiFpyvsj3A6bw3AusckWdU8cCIKcLieBSPeyWCPO/OT5l3VrOxd5BWNKLg9Pc63hFkoM07IOQn4A1tXp89fvUQRcs6x0GFHcDH0zdwCPc57c9oFw52rJxZaGvnjdyTUxjdJ5ysuJx5scU7obixbmXdnugK74Nw9YWvfEtRCh4WWERBaEY0FXGemeveniaVs
  template:
    metadata:
      name: airflow-jury-secret
      namespace: mlops
    type: Opaque
