---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-db-passwd
  namespace: mlops
spec:
  encryptedData:
    database: AgAZxy6OBrDbnxvcsNrFhUfEtqt2xlgo2z37qWCUz9/E+70jRM2uDZm+n2629+K6t/40Or784u0U0CfYk0L/7nF17enbKM0YtEyfhwqfs/4NC1WAuYQA8Y/fVrMhr9jv9MxuKZi5tZ0fODVWxHdDUVr4+JoWUIFIClkF/NnQs9EPvF6MCxtzIrneSdEDCgR1Q1OywGqsEEWhXu2sFKNTisxg70xXlIN4w4sObmAlCMT0uxwCCJxiWXy+bHKJVZgz3Zgbavph1mDeNfNb+fg5b/+PSw8RRoefCLQgEGhtaWEzHkuCy8QPHQeD6pFSNQb3n9b04xtsqHny0Jc+oyNyRCVE59V+t35U75mQ8qHkaaBY7ALGnKu1qApmhfZIG9ckTcLAP4awHgf02pF14mETNC7GfOP5KyLxM8mUwMAoE7/m9Nya+CMtkUoj/yn053jB9p7Ag1zpS8oGxuWnGkkRgsgTfpd4YdKQJCa5OExCJUTgN8AXd5eVXxQ4IctjVncRCeJ24+VAmmU2Rs2xF/ALfR2Yo4ft3Qfsl3GuEiLuvMr5ToSoUu+WZ7RomOVQsSwz54qZuCONeuOrgE3/gQBiBK247sjwHhLaRql9+FLlK2lffD/jpuwEZ0n6DQoy8ic4BbfWaJI1Cchoh7fLmASPtxZavZSqwUcexR7r4TIIlKohRvx/q2RiMQnqbXYfbdNloBZPFNKDWaK6ArSsFFt7F7FEHsp9LB4q7QtpFQThTo/KRBd/oEMxPH/tIaBZZtteRTFBhw==
  template:
    metadata:
      name: gitea-db-passwd
      namespace: mlops
    type: Opaque
