---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-secret
  namespace: mlops
spec:
  encryptedData:
    password: AgCJpT0JIundovA8G9/cTonFEf801CHGK1WlJWROREVGDJB3CkSZIem/5zx6dKlkgQ3zjT9vxsiTciPa0V4klLsdnS6otJdhNjpx7+MI+e12tefbDiq+kXoQ36qQaroAWCeaZ+eLsG5RZMFfk3B/+UODIZpjC+rBWk2XWbTnB8kGzNn4HnmXxpaW9rjc8/N/SOMQvUuhi9B1VdeA+9IXv98VQPDbYpqO6vKafzTIhlER4srpHSMD0feBsy6QF302RCLjr4bJIqm6X0jw1v8Cy7elnD58kLKniDXr0VuYmap/4mk/m1x7cprEF5urw7JhZrSZd3QlJHbWJ3Ig/IldW808I//6kCPxOPZUhNKpsibSHcwzIy5doh0EjNSQJeWdB3qwuc71rSictPfXDvfKfLOU9HLcFhsUsKSZ7oR9aAw+wStJ0ew1tbYzbV2QQJnIqbud2jR4bV/8nw+UNA9iEt/CwgpjXTsAzy3CccdACr5ZZaTC/WNIpqNMxXp/cuFFxpuGwmaBc2p0Sir6HGzaZ2fJHRImytSGhyTDmXG1mrTmq1MM9pYJ2PTxtzNJHSfzIsjHx8nLw30btqxz/B/RJf1WTbrG0jgCZio12u8gIVNeu9GdAEU5rAuTsbZjFCCvGnjndRTYU1mrVROeKNG5UsHFIp7Pk5l1Le6vDKBBQtzuTtcVOhoZ64n0fGiOhB3wF2bx3sLfTJV7+bSX3m8RNKkaE/BvzRqu9uqRUufhttnO3rXdKLpgEqZu
    username: AgB9hMRO3SdOdD8cnIWRqcfEFeLoRrdA+BJCqza5pja6zcgFV15DJ0cFWcTypLjuxnJTsCOYwVGGh+UmFe7c+7GM/l9RfUrkygozEMndnzN4vwMDMYZ5X598WQSdPuotXO7X+mFAHw8GFiZWJB6AeKiM5hyAkMwC97gA0176nK7hqDe8+JfwSo1LZGbOvX3UqVBX7JHGgJbZXdLImxejou2cV8aRSHT7v0500teQsiUg/PJslcwVLwtTrW/nKwsYDA3a2ya2scTwjbRUDo/Dqi+5wWt96ARbUebiZeTgTY5F1/ka6WEyomWF+vFb0r3wZBAqSDQ3j65qOuzcRCF8noQ5HG9wWSKW0+mQJyYrixeMQeV1rHrfK8h8PYTarr14Q1H26t/4hRMmzodUAwsJc/3i+uYXjX6MyuNsB1OXEZwrfj3VMd1dMCKtDAdwAbIIPLW3DO++93BH1pGYbZwqz5h5q6XOaM8TTNFnsQqGrp29+N/9fc5V1+ZcyMPYtsRImrhwtIaV403pSZut67P03Vd28eZSOdtcrXFEA5FVT177k8gJ/EoyukSSGTDBs3JwaTP1gGPe10/9dfSaScHUMlQQipYjAmSh2fffy2xEmANrakl8BZbklAxQxDa7eUt0jUqTzIvuhKmdIa2b/j2lDkPT+pcInL2H2IQr7WS474Wv9DthNsYyr+5/QsaCgPG55haneRHmQhoUNgLTIg==
  template:
    metadata:
      name: gitea-secret
      namespace: mlops
    type: Opaque
