apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-act-runner-secret
  namespace: mlops
spec:
  encryptedData:
    token: REGENERATE_WITH_KUBESEAL
  template:
    metadata:
      name: gitea-act-runner-secret
      namespace: mlops
    type: Opaque
