---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-secret
  namespace: mlops
spec:
  encryptedData:
    password: AgAGky6/PBjpj4cpEhoWXACj6ofc2OfezPz+R6MZDLi6hr+CCAcbRnb1PWueGQHIjDcWmucVLddswlsRzTKd3jEao1W1EuJWyf+jsJR7a8BYd7WTzRyMp1Bs1GjdSRxGp61LKKRwNiaHtFHFYMFtkyvDob1b0VVf48ojqjwjspxsA8H3yYdM7KaBZoz+7Sbr4KHzYoeQZ6DdcMhdIoP7/waekGdiX7uDKKs2+2XfbzFfIGnn+BAZQ//rYKFmqyIggYGrhC+pD/KoTb89TNdz+8taM3HRdTWQNPhtHZAP/tmBWrxamLCsiTbRZG2ZTVMS6gsnhbQEnFkSIPIkN6MIFsOlmuBrXgsHCrO2POBCK047St2tyZpCpm0dakfB74E81wka3r/KlngrclFFfIGP5/Gqa7OLz1HtAVW3yJlLiKySF496BxR/NJpNGe6PqHFWwOPfgJp1YYj8OUXJqfeWR7/KXNoP41BXw7vCNGdodIa9RPPA7s5DDfMnqv7G0I4D8U+PXMlzbR1y4Id5ISjp6oFrAxJ3mCtVrUwxClekyp2eZOKLxQkT6k1TtTOJhPKEq7uEJuY+WN+Ifz7pyketCGUZvzFUzHAMkNOFG1V89Zj0bwevLNFqBcv3d3OAxPran5ATjYt4qpqHs2y1oFWTnrJNmJ4TpzEJwyTRtd8d40CXtDr7Q50unZt/Jrx/MIPVLsom3/Rbtr+fPv/p
    username: AgAF7CpWnXkBLb2ohL4x0X+BBq7FXZ6KWDaXI2qxhXWxBqX7lpzDKaEcgXh9N/AsZBODyp4N9Gda2LTs1TtI7wdd5/OYWRJ86dmApcaIWJiF4jinYhjoK7xFq+T8CwcOvmISiCkI66Ar0yuXDh9cUGuKJRrtFWQb3LOHE4L2RGozT8D68edDu24/5HZgv3pBsBDyxzppMHSfmy5d16pzicA60YXrmCH3eN09p724PBWmwIRFiXKjXZ8mwhvFUqB0NqLsai011++EMAk1zZOzF8o+DZPthg9b+4O5QtXw3PdmWWLFSzijJXRb/iESC/+K/lPTTV1RI+9BaxE7D28WH34FcBh5Otc3qReOy7Vhiji6rI2eguLQ3YM7AKBlTHLPJ36hN9BrY4H2DPRbdaLvGrNmadqQyOEB4QkfY5ZX3c/p9bCLQP/9fPWXhuTlIBy90gpHVR9vBfadyF4D1CVsd2H5eBqJNlamfvwm03AwxiZxtOtz79zA//wp3rsvlBJJu3d5fvSg0xqJQAc94iG/vd1OfGb39JSxRoIj7DB/Bbn3u6mRm1GnCdH+2n+A9i1ph2h+dkpfmxigmTPMMowCiZOnnlDdYXkyxLe0GhHhJL29SQq/qzp4MyLTSm3erK2bFViVp9GNYKoFnlgJpkLl5mrC59z2DEJLvxlcdHTdlZJ4W1OLLMInwY46y2nWGEfdJXnQpqDCU47KJLjCpg==
  template:
    metadata:
      name: gitea-secret
      namespace: mlops
    type: Opaque
