---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-act-runner-secret
  namespace: mlops
spec:
  encryptedData:
    token: AgBYiUGVJ0RT5Fw72d7ZLUtCwVfmiL0dZQEPFZ7O84Y2UH1x8tOn9dWkjjZaTWJA0CWigzBQ48h0+Pg3C3gi17wfCPUYcp1Hb0dL+Nymfj9EF/5dvFHBoA0Scx3gvE9XJPwFzbKfaEW9bK2F9qrzYRAxKWRU9+UEbPcr/B/jR1F+k1gPJ0MIuvREmghuU0mNOcirKCFkK1neloLlcFdgPnC/JnoHbAqtpfTUlpHhymAP3WTvzAUwjifig4nY5YCtrn+6shXVNMOH73zCeiw4kOhxEgdJqXbEFYbBmgncnrwq+PTFo0c1pvW6EEQSwHYnZYXXKam7D563NOeGTX+GVg0ZMzhorcKfMSZEgG0/2wvhQXP26ACc85fuUHzduIHpHrK0rmvESCqSGllAc76+eRmDowXY705Uva8WQ91/mX/z+u5lZtpKOgCHyezAbw6QSzL3pZxEeK8wEJ6kA00W2X+xwXSKMVocETEKtwA765NPcqSoiBIZHNRIJ5PnB1QWtv7avUcYmmWloPE6A0f3pXwJ0mMKoz/9Bo1ydEtL1Cn1UYVlmaX/bHCHBgQ7yx4omLHG4pebK5+VU3KypVJKCM13/GhSMs6Z+FV7/8v7mjOg6HJAmaD2DgW3Uiy2vWFbBCq4n+KbPZtqvZpbuAtDZtDdUn/me75Uh1gBuckRtSsqm1w3QsSfwPdzujxpTmKCvF3HXDVQ7b9vnh6X8Ba1cH18RGaFVIh3x4iiRs4A3k3Vo05q6OxR7oNt
  template:
    metadata:
      name: gitea-act-runner-secret
      namespace: mlops
    type: Opaque
