---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-jury-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgB1vJ41DNm5KrlmBudefeaFu6qr/p+YHNHGYilhXNYGc5PZpCmQFrDmTfoi7vxs/+UgtPsBWuPNeNYVVFmtutRH9ecWMkdSp55ukYN9CxAlphMUFxamj6qTQ8WXVZ9I6x1UzMck8NF+3q/63EPbxPku0P3KNxE51bp27uW2L0GStCQtL43u4VtI0wOjdJUVGxxUs851LpOyfJytn6e3l4zZOcBN7FOw588SI/nDIcKig2AdZjwURtyPskfpFRWFbAoJgyFAJBuj5th14PnDauR6k9BUQNb6kjkLzfgBwgSGYbIjgdOubqw1ZBWPZ4gPuBS7LUN2LQnCdEziVHw5/K7o9d0ADJ5/K1x1JJKkF+ibhK/meR0h0rK5Q2Cw3w9jX5HokTmN5b95zJxTsFVG4KbhwCHICmcF2CS0kL20wSgG5Z0uORA3TpUrLjFfyUYVkO8khKiE5NHf88Je5YLs9vQY37xln3X0BxvR5mhWUZ1BI3Uhu6z2DxeM9eFChmMpm5Li2+qcUwKEyHZ0cc0cmMlNVETpvhazMAUCj3xKz0YhIX8xGn/rsdvDGzVjAeWYAHdqOOM11OkVmkAdwLh4vNJniR/DsbAAUSLH236PVgSdIOO9dPJYSEr7reCduLW8bXjTZmSa8ySzpJYO7xkGdtp8eBoYaHYvBz3BPz0UjuX544gz7CuE42yxLaZmjFm8pyoEYHl/r736qos=
    username: AgApl+vz4CVgUsgLiJYWln1HcgXjkg68rKELSnn12FF+9t6AbFhBAmNv1ppg82pQ0lIQuTeQNckBixCjYuZ0gem5VN1xIQi1r6vpjAmQO48GO9Kq8StNp6ejcJBQuUitNakhNF6tJ7WlVLo8+DKsBSpbL2osQLrK5nIREMye2MOytJie50Z08Sybu+8i12+8QLBii0kt5oVcc+1s+UMT0oqecHtcONTF4pSOFKYgD/x3fcy9twDnYEbr9ncCCZHmXWYJgdSCSRzyGOZXKLgiA12r8K0MK/wjfH7v530Zgr25o1Qvty+BgsV0nN2kdctWp1UuWwZoeWMSmyFL40bTKWohbJd9E0Rx0fPA+qtDKJKYxOUVwy41QeWK1jbziPzcZladWkYHvQ3/eAQEbEkkHZTIK0iY1v0g6Z4AvidYTGJ4y/xig95ONHfPxKCHa1QFigdTZaPmhbnFfP3wG/lqrI8eFr0yPoZH62m1qPhL6hythJu00ISYQnWoGtyGfjOFbm1snB/2QQjkcR/xjo8iT5wgZiU2ZuMpeK7POLtg85dktGjpRsi8JDlj+2PHGQ/iOYeZfJlbDoNKgM355QyxwhWLeBKs/+Ukuw3QTIl+4PutEmmTFlsK4vHlOsEPWCmpM0WezayPzmAeo3A5Sm3MfdHlhFhCcd8n/+3FFuKrDb0eC1PJTQ3ap8S+4zjWcs3JfhSPD8s2
  template:
    metadata:
      name: grafana-jury-secret
      namespace: monitoring
    type: Opaque
