---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgBOz9zFHeBb5UpYNRN1Jv1z3vtObbpkVE8o/DW1DYPTMgK3yKD+WMMmRHP/pB9iJ8P4rEg/hrYOG1leci3UOfuYNctAyvR6MyK2IlaznPMsgnxH0Xl4MY9MSQ5Wva5yMN5e1SRjhDhH69cDkZer+c5ckNzTmF46bqnDE8Ikm78vBgCMSSnk33fes9ro2/UjsITPBUEon784AoZ0z8nPMyTJ1bDtLuVs48XpGOd7/2Ue52zVulpOyEY0HCUxFwgaGHiLv0FwALJ7NRO8dzahj4BIaEXiL9MrWrH3Hh6TaF36UgcVY3wUupCr651LLY1amSsda/ldmB9fla6YbyFuVKNEKdpaoZoLnJoSy6uUcaikcpCPDLa7kZiA6GR8cObBwFaeHGljPXPNynIEUNAjWhWXOcGCLercYreyuV4jA/CzypxK0ikXy24hAZn7tTFH4MsIPUONCvjwmlryHDr9vJyz48Pm0mmDcPCxqwqurXrOh4dbYkzcKkIcMR8ZTGMCypzcYtnw+fwa3+8gcxO7SJINiEJ1RAtvlBrKxpZBqoulGNX1+2/w93vuwak49Tx3CUpIrkWce8VqWNiH0yInc4ssWEow5ImIwBi9RvmS74/YnLRFoOngSa23b1Unm07f+c24d/pe9MoUQcsX10VU2E0uTcIYk184N1Z2nhnHFDle0gDOtv7D0UppfYtwa6BOON3k92TdygieagjR
    username: AgAqiyVjWo/KlraUVMRS2t7kkXpwlB2Z5hDWCx2AFRNjqnIvkjoNsvMA2E0tnzXneo/UnEN4Od4B8WGDM7kTXkWiWyifygf6OeDZGrHC0pwTY32x/N3yRpodWdyz3nb0nQMhAzdSNctBZn+3jNb1F+ZhQRJUNjImpvKlXWuypvqKD65eU1d+M4XX5sEAp7A721vcrXHpxezg2cAs2swKPa2UvIt9ycbsKsUBD3EDN267HewuH3juzx9kfYHoP6PDbHmeXdrwzJX2gYwb4EP0d5nsEY8jGWIvgxs/gQPZfWgANa9bGj1HOLBi9w4jz644O+f6zOPQUGxTXF+nXb8LkMU9FTGKzh3APZi0nUGQvuDq4tzWcWvTX3EOa+rmBeN0qzGVLCilNQ1tOqwhzX31Kht+Rjzu5em45awuQhBMSSgg1NjyxSGEOlvygaeU7OmDnAEl3brb5CVGbjteSwRVlm5ZY0J20XVqmwuZDJGQp1ACRjlNdMTzruQImCor1Gx0SQ3VfY91DD8LocvsU3UfrH5DjXKWj/aEmC605AXy7c4CaxQP3mqihWG9ZiajIT/zvyme4Eo2cjxmiCqQ8Omi3bl0uCGRvy+bI7LWUk6wEZtkmvDuga8eJAYr7mxWB9wALNmLKFFFyddQeVqOmWh/2ypuujBa1yhWIZAeIQf+YXNRCzqPic5CiHBEsX7msI+oMxC5bUefGABsNHUTopT2
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
