---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kaniko-registry-creds
  namespace: mlops
spec:
  encryptedData:
    .dockerconfigjson: AgBfsbLqP07jlwRZvn7tK0RnRgF4oU4giWmNHMeJgFrtRvKMn3WKJh5MmpWLuBU9VW5sZA5UcKPJDpcFr53cSxXCKzNqWGq8RAxxnqbKK6zbG30rUhAVs4IygNnfxb2bkNlJm4360glam0G+E/YhZ8dEO5l56yp2yF2bDiQOzKn9hl0syJ9j4amaBxcpcj3o2IBWoPJe96d2CwerAjaLRC7BKO8wjvC1yhFv3gh0NBrzPxxRcyN9Sy2GB//RCGtHkzXl9yMzg7kTSMTdouJOAVwOtxXggCBG4R6mgOy7IOHT2a4xXA0gysuKlPIK81gD/G4rkAdqvQkApgzbGMGG1JMIDeh14z/kI/QhO3LJ4MRUekHat4Sp9J3BdXPBlamAucGi8WqoABhLA1ScHFOqhZZUtz90IHFQpCE6ThMYOmu0FkVhSWiOc62gA/FHx3TOLbk6yeafS68Kw0qcKC1vlQJoTkukg1OTPn5CYqNAvZf9ZOmJRnEc5WCpgTPSAvKBitoZOCHRf5JKMpZn0NA5SkhIhUvm9HdTe2GW1iVYG6/0YRVj91FSzsD783bxEBtucDtUgs/gwY+77gNfmqE7Wa9cGudMjiQ+iNbZz1rXWSWXLMYBLiEYUOISwD3o6ekHDYgnxo8xo033WUq71KLwZ48nouHJjx8APznrlzNJCALoH7KL3uR2mOPbk/EpbJIzjkzmXnluc9VOkWluoVX0a2oB6szuSZtdkO+zfzfPbidmVrg7Wzlyr69bKr+3OY9g8d63+Tu61Raegc5dY8VX1t6zbM4D+vFZEJyIUAvLAcgc5pXaNNK2O3JLdL81Plp36iTHeZzD5zf4+SBnon3dNGE9ftbjxPHIHbZ9P2R5PjFwjUW+j4kZ47TztCBlAPgl2jTLHkkoWzmlMJZUzfAzXkUFhghxkkDQ0IQ/DOg2ulbBZO2nRIijEWXNA4X7fIP7DOzQsRDyY1qy7G6x
  template:
    metadata:
      name: kaniko-registry-creds
      namespace: mlops
    type: kubernetes.io/dockerconfigjson
