---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-jury-secret
  namespace: mlops
spec:
  encryptedData:
    password: AgAx5x3jkUD8s78ngm5lUMPHC4uu+h5J1rbIZgZBYQLIgpRi6bRUKXMFTNPX5Fg3EzZskmpwvaf4+EfFxRZOUsELc7gGAI+r5uICd82rDOjPFETLz2rFBXwturQbwjb37hLiycAwzpM+TkCc0uYC0cwmWh3ZYexpEcngz4a+nUig/eG01LVtR3hZXRMGm6NZwFx5nKLRFa6PvDC014zNlJ+VOIPDUsCmG8+Dl1Q7jUDXr1iH+FAn2PuV1FVMBhJbjQKiMk534M2Qe9/kWcX6QTUtCCpSXln4YIcCZgzjgG8eGqYuBypRIdhGsEWONoQFw2uOFhDzLRXMEfncUDXQQXsHlAa1RFCRzeRlgfIxykjWf4F7ySUTSXBGLfiyKPSWQzDLlMf0z06AU4V7Lm1QTSzUk4Ob3AYVeHCx8Jw/E/Dssv/34Ic3JyODZgn0ZyFSG1N+VI7/q81aXuXfmyU/3+LpHRDmZDtZ0FNzTnys3Vy869EU1Ii7plKhGn0A98UQbcS4iBzSQ7GPy7tnJ7eqESy3M0ZhsLOVM1IzT5bSGU2AnIV/bcYtfWGq7QPFt1sFj/rkIIg4adX22l3YmIHcEFNAPhmB+LG9AHwb7aL52SlYWenY2XW3UO1Uoe4QJ7/XFtwElr3vKNyuEu8N01qaAzjQtpFjLXanp5GC8WRPFwIyzUj6KOOB4dKgCI3z3lqIavWyIBOOrt6wrOw=
  template:
    metadata:
      name: minio-jury-secret
      namespace: mlops
    type: Opaque
