apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: mlops
spec:
  encryptedData:
    root-user: REGENERATE_WITH_KUBESEAL
    root-password: REGENERATE_WITH_KUBESEAL
  template:
    metadata:
      name: minio-secret
      namespace: mlops
    type: Opaque
