---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: mlops
spec:
  encryptedData:
    root-password: AgBdrDAMpU4UaV+0liIZ/C+97UEvx3B/KNvov3CCG2PAYEkcZgzYVLN1cXz0VlePL+Uuzme9m2CLl553StEOrzel/iUegQ+NC8izNC+r6QtM7V6mWAEY/A4xICXUonIA4nthfQdCrX2YTVyrZnSwGfemB/is9JOrZHrxX1EyUfViO0jgp8tX7RunGDHibxR3EMgmqnHo4emoKDT/anJD49C+IMXC9hNNvJAGxccVbxEp6TnqSsCSIkYHMr0ribKVaRu9CsO01PrQ0kAAq34ePnYhgAz53SWkLYvotVx3Lg8h7dGHX09er33Ma4krrM/DCVf29FXWelswZqr6jUZawZVCWv6h5QPVfC8EQay3PxWwCdM1cI2elgS1G2cg5gsoJdsvrr0/3tFyLX6l0goutTh6cHdIBniQx7Aea14JsLW6dnFploe3bTaEbPx1pyb7YgusNJ04ECuzcar8XexjxFW9uoRZERQ+HwFXFEV6sfOMACJex8olz/VZkoQt7Oemf2DNw5nmm30Na2gXjzPvM/S6O2zjG+a7xW5QBWQ+07MtGtR5zF176dSIfEeBudGJgZWbiKy/8rDA7LEzMYUK6n9vhRWu5rjiLgshUQ/Wn1YBQpnwl6euVRqHMGPvgl5jT4z18iKpIbQwBsUmkVKYODdaKPixGpqZPj9jobI80RHHunI6Glei/32iUAVnfCUwuqIMJmsjQa3oB8unDMqGCAiqHdNMbTW+KuCV6qbiEBb665eLCBbjcwoy
    root-user: AgCS2ZENCrxan2llpo/+l7f3w68WF3d7YKprOMY5c6YPt+przTh+ar8eEXw4IfW/b/P5ZBcZZqHR7ZhqC/7Zc8VoJV8j3o/UhG83XwLSQrDTXn1/+H2yZy8kB/PRHaJNQNCTXm1IyQnhmUo0Qnwz/cc8Y5F+7T73UzwK6eW9GdyhNDlIoq5JsRGAIZqQJ7kGjJ2Fku73uCwp/s5ATpibz5sD87FK8alyoXdxN3ety9dceoRRAjU5jd01lZJe+4M/O7lVGjBsiM+IcyeGEtoYXI4LVU7znRvGBWEipixdLgjw0Iegi4OMYLU9mFTpmUu9DKaMZDrx3DzKnIzRMBjk+iNIehbVTSV8INpF8X+/tbDxhUmL0W/2vocylZPWzD07ssjfK27Y+WCGGOzAjk/sS/PJEAo4CRt/C/XCWNej4GzaCBlWv7jCln/Lyj35lYRWfnVzbGh2RhAqyBIe/cPdkD1gelHLUM8j+c/ihHqIM1J5a345YSyGa33VBiqzpC5YzUquzaL3HC17si/cHM1hhPAvvVbzNIL+V3qmVt+q42KAxFBgmCfbhG84e/0mRyJHVZBjZ0PRwX+QxC30IE0OHkPVaqA6JHgtikXIhbJgAjNBRwEUuVsDbob2SwmMOy+L6Tx7hQwnJOabzL4aqRs5gbj816FSMH7eoxijp6aiUZFDU+5IkQ01bRqXrHkQEvgqHwuk3y7FVtpTLayO
  template:
    metadata:
      name: minio-secret
      namespace: mlops
    type: Opaque
