---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-basic-auth-secret
  namespace: mlops
spec:
  encryptedData:
    password: AgBdrj90UTERqmTFQSBngb48LsxdEz6R5MUM/FFDgN+8V3PyI0CZQGfDY/xbfJoImccxhOZjmcRslqwieoho31GFapO5KQx8fJ81W8PXVU4eNh3dMEqxplPtAWJFG8O/Vbw+phNud2Ey0hlLW/LtH6L5/SfL5NGNO6oNRP/bd2VgSvFK6EHiXOP1sOGctg8kReKqJBzZw+MUKyoS1dldp5ehHz5VMGr3/mGg/4VUpeFy2nd/RPGy7i64IJRPjopQ81RxvCZUCvPW2KlM43d0c3IumtFWBoQVCnSA2UEHfO70acOxkmzQGvnA+1Hu7Jn/jvvekk1keg2od6DYD6BXaM5qdSbwyxEw6NxRwOS7YS99sTRfULT3foUCnAIoUiuzsUaxtD8YgtPwMB8LCEwUo+rfKCP+Mg5+Fipa+ZvoBMZbJLtFhKqNeyajN+EPVXBmB7SNYfkVnbWXA8p42HN+C/hUVHKAq9a45hsZ/f9TSdYSRykB4PEr7chfIqtdRYS4DHXwxmHFa6HOI3nntwPo/FHKHOEMBxycD+59l+QoQNVEpljoTXvw19R4ZzpJOsyY1Nd08WJWRM2lxszr0ZKcV+2TBprJh/HegjpFgs/ayqQbYWX3iGrN5Gju9AKeQ7718EjD03ReiRTeHMm3nPiBwAwN85vwMTaPSzcx2Oytho1jIsxvztFaVtcjAmdpnc97Bk/FxGqEC3wX6lsiE1gI6l4=
    username: AgAHaRi6jEkPWXCB7wwiSZGZHV6xrp5ROtPJs7a9C8Aq9CRfqYCRRalvJsHmcA+klaQZuRpCmu/fXqiNcHdhnTFrt3pIWRtuKgrqixrrMeVCXLhAN3JBFx1ScW+uT+z6qLLFP+QNtznxFbITE0oasY5j37tTurcfgdlagTOYURAk0+BmM12KsiMvfwwz2z4h8fraUXvo9KLJF/xiOhbd4zsciuuckPleQs01KGws+HG08Pa12wXGNo9J2+t8tw/KWpzxJgkuizS+3o+uRvxVOT89AFajcZwJVerIF2j/8Dgh7jq2KFKlaCtK4Olt6PezT3RoN7tNuPuERRzhcVIfQAvyDHBy+4XUusOiw4SojeOOXLsGNW79U/9Gh4eb+eyw25tFje+QyRlc4QooEMT4UXm4Jn0HFOS7BxJUWICMNgnZbxOnPqwL8PjbI5t5lwrECPXZLehjJHfzf3P+SErPIJzogfk53s+vj2TovP9ZaUiPxEscnUj14PLbNBVcIxzqY/G7XvF/nViga6lcOnARRsm6sQy9WWhYkNKhRVTApi7LFi/JC56cubJ1XahO6buJd4tEsduIB2q6rva5bbikzUIqxTjZsX2GvUZseRXnHv/yUxymkJLjxGKGiIhoDbIw+supDFoAkOhQAeITls+KjYJOK8TgdSNSuQqRtBUCTtFgKA3jQ1dcTerT67DguposPJuRLPhNSYM37eAegUo=
  template:
    metadata:
      name: mlflow-basic-auth-secret
      namespace: mlops
    type: Opaque
