apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-basic-auth-secret
  namespace: mlops
spec:
  encryptedData:
    username: REGENERATE_WITH_KUBESEAL
    password: REGENERATE_WITH_KUBESEAL
  template:
    metadata:
      name: mlflow-basic-auth-secret
      namespace: mlops
    type: Opaque
