---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-basic-auth-secret
  namespace: mlops
spec:
  encryptedData:
    password: AgAvXRJNz8l/3EHoyfgHxHuWdGFlXPrji+q7A04ggS0XBy4NpXENVWz9b8oGxN1QXKgRnkp9gGoODebto5D1Pg0Zob9Wly5a9g5+lGc1Vnph9MLBoDavbLe+WHEk9DMbTrX3dPO7XPJdPoJ8SuFFUafoLSW51j+S00s1UnxMYehs+Giu32piMQFEHmZN4jVNBUV0S8uIpFUYgxOZKkWzz1BqYIsiYsKVNG79uTudqmOeSKY9tEKVoze99kXx0XuQGui0n2DSyqeZv92oC6Exr8vh+ER0jbQg6ph+C6it3Rc/QmFv94SfAgC2DcgtH/1vAeio8aHJ1DjQ+fjpzPdWaFlbgO45B83itLfUzJE0xLN2sPUGrle0gkGiHM3N8k1ylAZLib6meVf1halq3Dgz1lOzmEBrdRC2YsUtZeBhtFYIPvwYcKpvB0p347Rorzb4VyVd/jaCkdhfuW0r5pRNymapJQS0GcpMxzJu52PVHEemXSxar27J0dgZgSH2LCQy9AcR3k8nC0ATdENyLsz89JcvZwcEft9xyTCtPHfkYE2mAE9JgPrcjgHsaeexTHRhLNh3rAB01SKVFNlCr/PbzDNmDd5zOolxST73EakNd6jyVBM04OOVcRqcifDDKGvVMcnAXQaym6Eij/PGf1/fdSAcRSK0JWKwbsoLefOSGlkQKdUpkRLfW3hYqfbqTRz9YuQl9nArd+bgirMgJkJHvQcMBzKKf7zoR0URRPmWR67VlkxPUCDIniws
    username: AgBd7lPQxPkKCfpKWY30t15XqJcpnUPuhQ4QcFrYqtuzKGRQBeyjXhDCRh/tIbRbf12OixemQ2yJxl5G4LTlKB+3j5fO/PVEzNJewYLDBpsGzF1cQ6eWCuaJLEwd7G41Spu5qE0Ed85OY240UiupCyE4E7ealzJvNKKgR2/poiyKjJ3eNb0XU292ABaf+Ubh6Z1NizzFbtZECtSentRtpjZf3FtiSsdrAICZ8Q1KrVfN5cONDsK4eMcVS6PT0BPjlXjRJZRlIC4lknyc+E9RkEMn0aMMJ4LeqYmgpGLkwGQekj07mYzRSLC5PSnL6e7R0c9Mybj8DxQd/A20JSLv+7wYl1ETgdJyuz1oOorlERvmIlu2KhEt2xqVpU442YtU0IUX2h2SLIhxkgqMT2lBgVr6lRk/QqWMtICufy3FrynlkGfaKF135z9acIYeWWTDA2lVik+7+kwcqj+tz2jWQ+kHhtMH2K5BeaagEdntV43XID441TGJk479M8jgkuxN5nePH/rdL/RzXUeCigfiGEDesGwrFr5vCnqA5q+cySBQ+40CgyutjRAtgw9jkVd/WozlAfEWqfLPLpy5xTnF9QxSReFDHCxi3d3AUn56jmV6/mJL3iqR80524H065v9smSzvTHV84weBZlDVpP+kbWzHQqXhQvu02Tl0LhvLpxWeAcFRPkVL7syM4gg72QqjlHJKurFiO3n7ySP8rUU=
  template:
    metadata:
      name: mlflow-basic-auth-secret
      namespace: mlops
    type: Opaque
