---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-jury-secret
  namespace: mlops
spec:
  encryptedData:
    password: AgCXp9DphF44To7u0C0AlL1/2guJ9HBs+vFX6mzDjG/DOJXhms8HOY2mi/AXRjfyzXbnbRcuRAONjtakiQB9MnZPamYxG/JhS7VmGRLdesmGvfMwI89UhahQcJ5cLHQ949gHz/yBlKdEV2f1C7g1xBYxHTSfLIsHhv7I6qp+uI1tEqTNRUojz+lnJKEZ+JUb+lCrTC/dIKbJVH8M2SWU9VUYCw60p5dOUmQmEd9uPYLUCsdP6LImk5zm4W1vzhFdlL00jv5r8SuWy9wN4Psd2hzFY2nPTxHG4020ztc1c11P/XP0g1iTvUXr0n/mXAyG5gBRPdI7CM/NTupv0ovpEgNL/9+H9jJfPZWh6V9LAP3rBgWFR6Wo4z5Ui1yRqceBTQgpfpMyCgjh0gppr5aaIBJBAYTZ0TSoIgY5VBPtkXuWKfZVROh65E20erW5qoPTb0DcUCTJEacSWvsCAHHKdExB88hNdcapEcGb4qAh+4QgGjGZLyigS7iqfnAhout8UEiUK8tqbtWbW/e9V53ejyLk7r1Vlmh+jqeEACRRQqhUGkidYwm8bDK2ouaQI+/ScoKeAts8dEtbozhkuSp6kont0mwM7e0ljYRku4eBKDL+ndqXK9x+cuyF3keUq/B8Oaolu3sXQzcVAXOa1QQCgcpY3VlTiTboGPP67e9YeAnBjiu6lYiCd6m8qZacIOUV2w6LQtwhoHQtL8mGB8ktlg==
    username: AgB+96huGYE8gzs5m6wtDj05wrUxuF/aIgGmieMMsLJmO1dfM4EGOH6R1Ui1tDT3vs+7zYZ4C7/EGJOwWB4kWnaGuPk2MAgZldAqgcI5DWHP2L3Btt6l2a+pxGJSDeko9nz/ExRMUYgVz3g95zGgHHaJ6NE53Fn6x4H7zaJr2mZ29AF/D2Hz6jIBJPFpADUgwOl4o0ZAtzrmRk+ghqyeDei3NN/xnzDlTtHVVxDDU3ICV1n55VGRVXCBEkBXwHe/htXVmGGdCgAjppTxMVsTlYlovs5tqpFFxhihVjXj7kiOhhsqMqcNjrFvBFTJHDcBggUbzlHAULtBx0tzA007lMuEPXMOEmDG6VDG8cuy1rnqjoPKwrYLvGAkTlxlZyRfKRiHe+mPi8R3BS+UsaZRQYzZ7Hmm5DQqimDEp0p5EOzlaKRYe98p8VtGV5eBGGTT6D/Wq0g/rP4a8p98ZMFfypbPzMjTYXl3zTgNbnz7gDjD2CbN9nFeseNemiArFqUOejfvTtHpetiyusFXThBfTAFQ52P2clwod+ApjYR6kIqSJEVX4is+nM9JVB6JMfeXDAzlhfj8D8wHDRBqBp3qo4R+hfV9AZlpC1Kh8dqJNkn8vsh5rx3je5L8wG0yjeEbCKTGFPUg+nvNF0teu5YZk3vNdDvSSRvSuu03Bp0xAYSh0mtLCByu2EGkAbktyA7FxQO/EYUF
  template:
    metadata:
      name: mlflow-jury-secret
      namespace: mlops
    type: Opaque
