apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: mlops
spec:
  encryptedData:
    postgres-password: REGENERATE_WITH_KUBESEAL
  template:
    metadata:
      name: postgres-secret
      namespace: mlops
    type: Opaque
