---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: mlops
spec:
  encryptedData:
    postgres-password: AgA51jmMBHCjNjulmdaPw6DkPKRhFRZ0nv+JPvzvyHnDLOhpBNc+P009hvNK0SbNshrN6L/isw3Rgu/JL4eqnYnE4XtBEPZmhrROIxl2xoZgBxZ20GHYSEdftm9WkWrzdAq40TTkKVhc6KghzuNOfskA/WUnIF+Ah6UC1YZG1NJ0RB4USpit2j3ujWzuh0fZ1tmBWC1iIOxAzqoXVIPomzKmVuzQPV49rJavU1x3gRxTZLaueI9+u2CZk44pojf2WMlYRNtUTenB/D8rJQXwewcBzwTZqhl5w9ZOjEKksPts796g9JIBKJwyPvgl+E9AZXrjt/jniCBmIUEpEv5SWdhIhvar3UC8Jzhvvxlu0HdVmZfD9HIzWF/JKKqcvkoLKiYWsbzqxrzgcKl14JteGfoNngI09vVoBKTcDDjF4eN/wtGMbccEzhbztwXHPSGvVH3Y81wWRp55JUyjQiLGbcDx/cO0HGUUqcukiw1xgeuzF4pH01PKAzfi6l61RfDcAsEHkhkan6Do21PmVsReV6+cIklrv4GjRAKrAHOV69XoHfQpVcUZft9USAHy2dYpvcLiqhIoaSvwXzADVYgAaoChJsZwS7cf5tQfVb1ZTubgUAKn6ZtOgVSoBx3GpgJ34MJxRUKgUMpG6URvggfFxBkOqtFKwHMdpEEVQ+B+Vn83xMGEbptz/uLNB06jq4wSQFzm77suEqSQTbeCJTE7yvLRmeidIYiYSPVudb6L3utqFQ/oTHrQJRKW
    postgres-user: AgBnFSNFUYeop9/3eHC4KjGsZPhlNnY0wDcXKlpWSXxHG1UsioYFqH996V6VqzaiKg8OEdEcZA+nXqy17jqU+lDdMUWQx7I5aR6rTfLMoYq5gtb3pCpqycZZoZH6tiRAHt7+nAWeiMkq4XW8KKbU7ukAkIhaMGYgkh4LS+z7JF0rUSXe3+SmINaBQz28Nv3mFKse7QQnjKlImpWVIs4Quw2+kc0EelydbuEv5jbF14ccQlprwHW6UgOGQ3PtqhZhX0FvQJOdb8F4uOxc/bJ3oB+ewLJTlVeNgDqu8/nagCDzlMNzSl3vtOpMWe6V+E68vm50NdgIpsp1O7Hk8r5sQn/28ybshuuaX149WhX3jZPCXUYz9IkSn/L77F1e9Z+2F0zes6SvEO+VQ30kwUxdeOzD8dF7q2S04P0pWRB2udKt63afPoPphCbYlKXWl6pLd4AC3sjB7oAcdHKsapYbIT6wKDlAXTIE3qG4mTtfWlWvSFDo1SObqXxcewE7YNISa7AoM9mHJYLDSWM4X32Zgg3UgkFJed9BZn4ISAocX9fWywAlNujrHxInXfant2OHje+TvqEs18rzff3MVo3vIsgwErheM3IWtQT1xwz1UEVtxGr8BX4H/fAnlUE55zv2GvsEpuWhWxuyt144I/kXzO6muiWDCqxJr5lV9GW2djrVPjwxWUIbjyrx9UI0gjd5cPh7Nj44thxQ7w==
  template:
    metadata:
      name: postgres-secret
      namespace: mlops
    type: Opaque
