---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: mlops
spec:
  encryptedData:
    redis-password: AgCZ+grA3nHLBnrtIVRzMMSi2wdDLBPyARmMY1uvjodD7Od8QbLHR95vS51zSrBbnCHGcKKyPxd53aSe3b61NUt0BfXJINx20/6jVyKkptDFLYy4Z11EBYaA5bVooPgRLMNjAYqCR6NQI8lTEISC3p2JehHENxXBtuK+oXlnka9Fyr/4KIYH/Jr1StIAIY9sKqiHE56XQDvzaFFlkwlP8Stf2ht2YR07kRfyjKGGzPkpILJSgJqty4cDRj0lGkuAriGbWwuW5frXO6iYHy2mNxa6pEy0tMB5ODVlrlXnTU/TC5z8UJdYjHuuKyEkZR5u8HJy+6C4KTmchtvmpt/hLpPPeZ24AQh6UN5yAkrbXiw3AgqmwJS8y4w0fZ6G+Ji1WISrx1+SsJAiFmECuGQDvvyYY4O7i6dRJtXQzuUffIg1giODlzqdIqGT2QExY7ezxxHCWtBJCYuhoVURlNT7DM2Jm0eneujlhiS2s51BXYIaAP5RcGuJNPU3QPjLeraZt3wdtXOyU11IKGZ39EmK98GQsaGlm8hEbL5rPq8DJ7GYqyYLtaNw+9yW8ZHPZLgzQG15rkxg26S8P+1Xq5PM/YrW6foyZ8CjRl907vx1ANG7bIBB1+KlyjoyrQD+EuhaCKISAS9FGoyE1pkdEoNEwvW6I2yFNHCbdjgc72Sd7qYB0wlzcMePtuJocyduZL+p1duWhw7uPRYIfBV2iY74IyNtBsQP4RLEZMTb5Yujhbxwq5zHstyQ3f2k
  template:
    metadata:
      name: redis-secret
      namespace: mlops
    type: Opaque
