apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: mlops
spec:
  encryptedData:
    redis-password: REGENERATE_WITH_KUBESEAL
  template:
    metadata:
      name: redis-secret
      namespace: mlops
    type: Opaque
