apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: mlops
labels:
  - pairs:
      app: frontend
      env: dev
images:
  - name: git.alexshishin.ru/mlops/frontend
    newTag: c0cea1c9c7893fd5c5139fc8a6205adeec32a574
