apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: mlops
labels:
  - pairs:
      app: frontend
      env: dev
images:
  - name: git.alexshishin.ru/mlops/frontend
    newTag: 662f0446c0d82a248d2a789b073359a20d7d9dfc
