apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: mlops
labels:
  - pairs:
      app: frontend
      env: dev
images:
  - name: git.alexshishin.ru/mlops/frontend
    newTag: a95f7abe14b6a2a677a30d84e78c08033573e045
