apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: airflow
  namespace: mlops
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`airflow.alexshishin.ru`)
      kind: Rule
      services:
        - name: airflow-webserver
          port: 8080
  tls:
    secretName: airflow-tls-secret
