apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - secrets.yaml
  - cert-manager.yaml
  - ingress-tls.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - gitea.yaml
  - gitea-act-runner.yaml
  - mlflow.yaml
  - airflow.yaml
  - serving.yaml
  - frontend.yaml
  - ingress-main.yaml
